package br.com.lupainsights.audit;

public enum AuditAction {
    AUTH_REGISTER,
    AUTH_LOGIN_SUCCESS,
    AUTH_LOGIN_FAILURE,
    CNPJ_IMPORT,
    CNPJ_CANCEL,
    CNPJ_DOWNLOAD,
    CNPJ_PREVIEW,
    PRODUCT_EVENT,
    PASSWORD_CHANGE,
    SUBSCRIPTION_CANCEL,
    SUBSCRIPTION_REACTIVATE,
    CARD_SAVED,
    CARD_REMOVED,
    ACCESS_DENIED,
    ADMIN_ACCESS,
    API_REQUEST
}
