CREATE TABLE users (
    id BINARY(16) NOT NULL PRIMARY KEY,
    nome VARCHAR(150) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    cpf VARCHAR(11) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    enabled TINYINT(1) NOT NULL DEFAULT 1
);

CREATE INDEX idx_users_email ON users (email);
